[package]

name = "bindgen"
version = "0.14.0"
description = "A binding generator for Rust"
authors = ["Jyun-Yan You <jyyou.tw@gmail.com>"]
license = "BSD-3-Clause"

build = "build.rs"

[dependencies]
log = "0.3.*"
libc = "0.1.*"
syntex_syntax = "0.7.*"

[features]
static = []

[lib]

name = "bindgen"
path = "src/lib.rs"

[[bin]]

name = "bindgen"
doc = false

[[test]]
name = "tests"
